### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by adubey14** [RIAPS/riaps-integration#47]
We should create a script to summarize the installed riaps configuration. The script can be called riaps_info and can be installed with pycom. Please let me know if I shold go forward with it

**Comment by MMetelko** [comment]
This is a great idea!  It would be good to have a script output that users can provide when asking for support questions.  That way we can know the state of their system when the problem occurred (i.e. version of the platform).  I will also start adding a version file to the VM and BBB images that we can query for this script in a ".riaps" directory.  

All, please indicate ideas of information that you would like to see from other systems when debugging the RIAPS platform.  

Here is my initial list:
* Ubuntu version (uname -a)
* Versions of RIAPS apt packages
* Version of BBB image
* Version of VM image
* Eclipse and RIAPS plugin versions
* Directory listing of riaps_apps (to see any installed RIAPS applications)
* On BBB:  riaps-deplo journalctl output for last 100 lines (maybe)

**Comment by MMetelko** [comment]
This was implemented in https://github.com/RIAPS/riaps-pycom/pull/203.
