### ISSUE TITLE
Can't see bbb from VM

### ISSUE THREAD

**Issue by iliesaya** [RIAPS/riaps-integration#54]
Dear Team,

I have 1 bbb running the riaps image, with a private ssh key that I added with the secure_.sh script from the VM dev environment. I edited the file riaps-host.conf to add the IP of the bbb.
I can ssh to it with this command , it's working
`ssh -i /home/riaps/.ssh/id_rsa.key riaps@10.76.90.1
`
and I am seeing it with sys.check :

`riaps@riaps-devbox:~$ riaps_fab sys.check
=== fab -f /usr/local/lib/python3.6/dist-packages/riaps/fabfile/ sys.check 
[10.76.90.1] Executing task 'sys.check'
[10.76.90.1] hostname && uname -a
bbb-e59a
Linux bbb-e59a 4.14.79-ti-rt-r84 #1 SMP PREEMPT RT Tue Nov 13 22:30:45 UTC 2018 armv7l armv7l armv7l GNU/Linux

Done.
`
but when I launch RIAPS Control I don't see the bbb, I only see my other laptop runing an other instance of the VM dev env with riaps_deploy running. 

What did I miss ?

thx for your help

**Comment by MMetelko** [comment]
Double check that /usr/local/riaps/etc/riaps.conf is pointing to the [network connection where the BBBs are located](https://github.com/RIAPS/riaps-integration/blob/master/riaps-x86runtime/README.md#configuring-environment-for-local-network-setup).  All nodes need to be on the same subnet to operate. 

Also, on the nodes (BBB and VM), please update the permission level of /usr/local/riaps/keys/riaps-sys.cert to be 444.  This is a change that will be made in the next release.  Another thing to consider making sure the new public key is copied into the authorized keys on the other instance of the VM dev env with riaps_deplo running (another planned change).

**Comment by MMetelko** [comment]
Assuming based on Issue #55, where progress was demonstrated, that this issue has been resolved.
