### ISSUE TITLE
Base RIAPS SD Card Image Creation fails 

### ISSUE THREAD

**Issue by shekharshank** [RIAPS/riaps-integration#61]
Base RIAPS SD Card Image Creation fails due to few errors during the execution of base_bbb_bootstrap.sh related to dependency and file location. Attaching slightly modified script which works. 
[base_bbb_bootstrap.sh.txt](https://github.com/RIAPS/riaps-integration/files/4575336/base_bbb_bootstrap.sh.txt)

**Comment by MMetelko** [comment]
Thank you for the catch on the touch statement.  I am curious about the need for the other two changes.

1)  In opendht_prereqs_install, why did you comment out the change into the arm library directory?  This was done to go back an setup incremental links to the .lib file.  For libgnutls and libmsgpackc, there were no base .so links in the installation (i.e.  libgnutls.so.30 and libmsgpackc.so.2 needed a libgnutls.so and libmsgpackc.so soft links to correctly install the opendht library.

2) Why did you have to move the "other_pip3_installs" up further in the list?  I do not see where anything from that was needed by the calls in front of it.

**Comment by shekharshank** [comment]
1. After opendht_prereqs_install is externals_cmake_install and it fails at
 
>  cp CMakeLists.txt /tmp/3rdparty/
as the script is in a different working directory

opendht_prereqs_install did not fail after the change, however, if the cd is necessary, then an alternative could be to give path of CMakeLists.txt in externals_cmake_install

2.  pybind11 is needed earlier which is installed by other_pip3_installs

**Comment by MMetelko** [comment]
Thank you very much for the suggestion!  As you can imagine, as thing evolve it gets harder to check everything with each release.  This script has been maintained, but not run fresh lately.  I really appreciate you providing input back.

**Comment by shekharshank** [comment]
You are welcome. I am working actively on RIAPS, so I would keep reporting issues I encounter. Thanks for your help.
